# Site settings
name: Zine Cultural Reviva
title: Zine Cultural Reviva
description: 'Zine Cultural Reviva, primeiro zine de Correntina. Aqui você encontra todos os textos publicados nas quatro edições do Reviva.'
url: 'https://reviva.radicaos.com'

# Build settings
markdown: kramdown
permalink: /:categories/:title/
plugins:
  - jekyll-sitemap
